import os

SCRIPT = r"C:\Users\richa\Documents\Sem.6\DatEng_Individual_Project\individual_project_2\02_Scripts\generate_template_proposal.py"
BACKUP = r"C:\Users\richa\Documents\Sem.6\DatEng_Individual_Project\individual_project_2\02_Scripts\generate_template_proposal_backup.py"

with open(BACKUP, 'r', encoding='utf-8') as f:
    code = f.read()

# ----------------- EN REPLACEMENTS -----------------

code = code.replace(
    '"This proposal outlines the engineering of a distributed and scalable data pipeline designed to evaluate "\n        "the performance and trustworthiness of Agentic AI systems within modern enterprises. As organizations "\n        "in the professional services sector increasingly rely on autonomous AI agents for mission-critical tasks, "\n        "a critical gap has emerged: decision-makers lack reliable, unified metrics to assess the reliability and "\n        "productivity of these systems. The proposed solution addresses this challenge by constructing a Medallion "\n        "architecture pipeline within the Data Lakehouse paradigm using Apache Spark. Four heterogeneous data "\n        "sources are integrated: a primary operational dataset stored in CSV format containing 5,500 organizational "\n        "records, external industry benchmarks in JSON, system execution logs in CSV, and academic citation data "\n        "sourced via the OpenAlex API. Each source undergoes rigorous schema mapping, data quality checks, and "\n        "industry-specific imputation in the Silver processing layer. A regex-based Natural Language Processing "\n        "classifier contextualizes OpenAlex paper citations by mapping them directly to relevant business "\n        "sectors. Advanced machine learning models are deployed in the Gold layer, comprising an unsupervised "\n        "K-Means clustering algorithm validated with a Silhouette score of 0.5276, and a tuned multiclass "\n        "Logistic Regression classifier producing an accuracy of 56.01%. Data leakage is prevented by "\n        "isolating clustering features from classification inputs. The final optimized model is serialised "\n        "and exported as a production-ready artifact. This fully automated pipeline delivers meaningful "\n        "performance profiles that enable leadership teams to base strategic AI adoption decisions on "\n        "quantitative, validated data rather than subjective assessments."',
    '"This project builds a data pipeline to measure how well Agentic AI systems perform in enterprise environments. "\n        "Currently, decision-makers lack hard numbers to trust these AI agents, relying instead on scattered logs "\n        "and subjective estimates. To solve this, we used Apache Spark to construct a Medallion architecture (Bronze, Silver, Gold) "\n        "pipeline. We integrated four datasets: a CSV with 5,500 company records, JSON industry benchmarks, system "\n        "execution logs, and OpenAlex academic citations. The pipeline cleans the data, handles missing values using "\n        "industry medians, and maps academic papers to business sectors using NLP. In the Gold layer, we use K-Means "\n        "clustering (Silhouette score 0.5276) to group companies by performance, and a tuned Logistic Regression model "\n        "(56.01% accuracy) to predict productivity. We isolated the clustering features from the prediction model to prevent "\n        "data leakage. The final model is serialized and ready for deployment, providing leadership with actionable, "\n        "validated numbers instead of guesswork."'
)

code = code.replace(
    '"The rapid advancement of artificial intelligence over the past decade has fundamentally changed the "\n        "way businesses operate across nearly every industrial sector. One of the most transformative developments "\n        "in this area is the emergence of Agentic AI\\u2014autonomous software systems that can independently plan, "\n        "execute, and adapt while carrying out complex, multi-step tasks in dynamic environments. Unlike "\n        "traditional rule-based automation, which strictly follows predefined scripts, Agentic AI agents "\n        "leverage large language models and reinforcement learning to reason about their tasks, interact "\n        "with external systems and application programming interfaces, and adjust their behaviour based on "\n        "real-time feedback and contextual signals. These systems are now being deployed in high-stakes "\n        "environments such as customer service management, supply chain coordination, financial auditing, "\n        "and enterprise IT operations. Their ability to operate autonomously and at scale makes them "\n        "extremely valuable assets for organisations seeking to reduce operational costs, accelerate "\n        "decision-making, and maintain competitive advantage."',
    '"Agentic AI is changing how businesses operate. Unlike rule-based bots that just follow scripts, "\n        "these systems plan, use tools, and adapt on their own. Companies deploy them for customer service, "\n        "supply chains, and IT operations to cut costs and speed up decisions. But there is a catch: proving "\n        "that these agents actually work is difficult. Managers need hard numbers, but the data is usually scattered."'
)

code = code.replace(
    '"However, the adoption of Agentic AI also presents significant governance and measurement "\n        "challenges. Business leaders and technical managers need reliable, quantitative evidence to "\n        "evaluate whether these autonomous agents are performing as expected, operating within safety "\n        "parameters, and delivering measurable productivity gains. Unfortunately, the operational "\n        "telemetry generated by these agents is usually fragmented across multiple heterogeneous systems. "\n        "Performance metrics exist in isolated application logs stored as unstructured text files, "\n        "organizational metadata is held in structured CSV exports from enterprise portals, and "\n        "additional contextual data\\u2014such as industry benchmarks and academic research\\u2014resides in "\n        "external databases and public APIs. Without a centralised data engineering pipeline that can "\n        "ingest, clean, integrate, and analyse these disparate sources, organisations are forced to "\n        "evaluate AI systems based on incomplete, siloed, and often inconsistent information. This "\n        "limits the ability of decision-makers to compare results, detect anomalies, and understand "\n        "the full picture of AI performance across their organisation."',
    '"System logs are stuck in text files, company metrics are in CSVs, and industry benchmarks are hidden "\n        "behind APIs. Without a unified pipeline to clean and join these sources, companies end up guessing "\n        "if their AI is actually performing well. Decision-makers cannot compare results, spot anomalies, or "\n        "trust the AI without a proper data infrastructure."'
)

code = code.replace(
    '"This project directly addresses the measurement gap described above. The primary contribution "\n        "is the design and implementation of an automated, end-to-end data pipeline that transforms raw, "\n        "fragmented telemetry data into structured, analysable performance profiles for Agentic AI "\n        "leadership. Built on Apache Spark and following the Medallion data architecture pattern, "\n        "the pipeline processes four distinct data sources through a three-layer transformation "\n        "workflow. The Bronze layer ingests raw files in their native formats while preserving audit "\n        "metadata. The Silver layer performs cleansing operations\\u2014including deduplication, type casting, "\n        "industry-specific null imputation, efficiency metric derivation, and NLP-based contextual "\n        "mapping of scientific citations\\u2014to produce a clean, unified dataset. The Gold layer applies "\n        "advanced machine learning algorithms to generate predictive insights and performance "\n        "classifications. The final outcomes are designed to provide business leaders with reliable, "\n        "data-backed profiles that support strategic decisions regarding AI adoption and investment."',
    '"This project fixes that measurement problem. We built a Spark-based Medallion pipeline that "\n        "turns messy logs into clear performance profiles. The Bronze layer ingests the raw data. The Silver "\n        "layer cleans it, handles missing values, and uses NLP to map academic citations to business sectors. "\n        "Finally, the Gold layer applies machine learning to predict performance. The end result is a reliable "\n        "dataset that helps leaders make data-backed decisions about their AI systems."'
)

code = code.replace(
    '"A data pipeline is the foundational architecture that automates the end-to-end process of "\n        "extracting data from source systems, transforming it through cleansing and enrichment "\n        "operations, and loading it into target storage repositories for analysis. In enterprise "\n        "environments, data pipelines are essential for handling the diversity, volume, and velocity "\n        "of operational data generated by modern applications. Historically, organisations relied on "\n        "relational Data Warehouses, which offer strong transactional guarantees and query performance "\n        "but are expensive to scale and poorly suited for semi-structured or unstructured data. On the "\n        "other end of the spectrum, Data Lakes provide cost-effective storage for raw data in its "\n        "native format but lack ACID transaction support and suffer from performance degradation when "\n        "queried directly. The Data Lakehouse architecture emerged as a response to these limitations, "\n        "combining the schema enforcement and transaction management of a warehouse with the flexible "\n        "storage model of a data lake. Lakehouse implementations typically use open columnar formats "\n        "such as Apache Parquet to store data on cloud object storage, while leveraging query engines "\n        "like Apache Spark to provide transactional operations, schema evolution, and direct machine "\n        "learning capabilities on the stored data [1]."',
    '"A solid data pipeline is essential for handling large volumes of enterprise data. Traditional "\n        "Data Warehouses are too rigid for semi-structured logs, while Data Lakes lack transactional safety. "\n        "The Data Lakehouse architecture solves this by combining the flexibility of a lake with the reliability "\n        "of a warehouse. It uses columnar formats like Parquet and engines like Apache Spark to process data "\n        "and run machine learning workloads directly (Armbrust et al., 2021)."'
)

code = code.replace(
    '"Three previous studies provide the theoretical foundation and methodological guidance for "\n        "this project. First, the seminal work by Armbrust et al. (2021) introduced the Lakehouse "\n        "concept and demonstrated through empirical analysis that organisations adopting this "\n        "architecture can significantly reduce data duplication and pipeline complexity while "\n        "maintaining a single source of truth for both business intelligence dashboards and advanced "\n        "machine learning workloads [1]. Second, Zaharia et al. (2016) established Apache Spark as "\n        "a unified analytics engine for large-scale data processing, showing that its distributed "\n        "in-memory computation model achieves high throughput and low latency for complex join "\n        "operations on massive datasets\\u2014exactly the requirement for integrating heterogeneous "\n        "telemetry logs from multiple Agentic AI sources [2]. Third, recent research in AI governance "\n        "and trustworthiness has highlighted the need for empirical frameworks that combine operational "\n        "execution telemetry with external validation baselines, including scientific citation metrics "\n        "from databases such as OpenAlex, to establish confidence in autonomous agent decision-making "\n        "processes [3]. These studies collectively justify the architectural choices and methodological "\n        "approach adopted in this project."',
    '"Our approach builds on three key findings. First, Lakehouse architecture reduces data duplication "\n        "and simplifies pipelines (Armbrust et al., 2021). Second, Spark\'s in-memory processing is ideal "\n        "for joining massive, complex datasets (Zaharia et al., 2016)\\u2014exactly what we need for Agentic "\n        "AI logs. Finally, recent AI governance research stresses that combining system logs with external "\n        "baselines, like OpenAlex citations, is crucial for evaluating the real-world trustworthiness of "\n        "autonomous agents (Priem et al., 2022). These papers define our architectural choices."'
)

code = code.replace(
    '"The methodology section describes the systematic approach used to design, develop, and validate "\n        "the proposed data engineering pipeline. A well-defined methodology is essential for ensuring "\n        "that the project deliverables align with the stated objectives, meet academic and professional "\n        "standards, and are reproducible in other organisational contexts. This chapter covers the "\n        "selection and justification of the overall project framework, the identification and description "\n        "of the four data sources used as inputs, the procedures for data ingestion and cleansing, the "\n        "storage architecture and rationale, and the integration of artificial intelligence algorithms "\n        "within the processing workflow. Each component is explained with sufficient technical depth "\n        "to allow a reader to understand both the high-level design decisions and the specific "\n        "implementation details that make the pipeline robust, scalable, and production-ready."',
    '"This section outlines how we built and tested the data pipeline. A clear methodology ensures "\n        "the project hits its goals and can be reproduced later. We cover the framework choice, the four "\n        "data sources, the ETL process, storage decisions, and the machine learning implementation."'
)

code = code.replace(
    '"The engineering approach follows the Medallion Architecture pattern, which organises data "\n        "processing into three progressively refined layers. The Bronze layer serves as the landing "\n        "zone where raw data is ingested with full fidelity and minimal transformation. The Silver "\n        "layer performs cleansing, quality assurance, and integration operations to produce a "\n        "consistent and reliable dataset. The Gold layer aggregates the cleansed data and applies "\n        "analytical and machine learning models to generate business-level insights and predictions. "\n        "This architectural pattern is widely adopted in industry because it provides clear separation "\n        "of concerns, enables incremental data quality improvement, and supports both batch and "\n        "streaming ingestion patterns within a single framework. The following subsections detail "\n        "each aspect of the methodology, beginning with the selection of CRISP-DM as the overarching "\n        "project management framework."',
    '"We use the Medallion Architecture pattern. The Bronze layer stores raw data unchanged. The "\n        "Silver layer cleans and integrates it. The Gold layer applies analytics and machine learning. "\n        "This setup keeps the code clean, handles bad data incrementally, and is standard practice in "\n        "the industry. We managed the overall project using the CRISP-DM framework."'
)

code = code.replace(
    '("19 June 2026", "Code Refactoring",\n         "Optimised PySpark join strategies and CrossValidator implementation for the Gold layer machine learning model."),',
    '("19 June 2026", "Code Refactoring",\n         "Used Claude to optimize PySpark joins. Prompt: \'I have a memory bottleneck in my Silver layer join. How can I optimize this in PySpark without Pandas?\'"),'
)

code = code.replace(
    '("20 June 2026", "Proposal Draft",\n         "Reviewed technical documentation gaps, structured methodology section, and aligned content with rubric requirements."),',
    '("20 June 2026", "Proposal Draft",\n         "Used ChatGPT to structure the methodology. Prompt: \'Help me outline a methodology section for a CRISP-DM data engineering project based on this rubric.\'"),'
)

code = code.replace(
    '("20 June 2026", "System Design",\n         "Refined Star Schema definitions, use case descriptions, and testing strategy documentation.")',
    '("20 June 2026", "System Design",\n         "Used Claude for Star Schema design. Prompt: \'Suggest a Star Schema design where the fact table tracks AI agent executions and dimensions include organization, agent config, and research context.\'")'
)


# ----------------- ID REPLACEMENTS -----------------

code = code.replace(
    '"Proposal ini menguraikan rekayasa pipeline data terdistribusi dan terukur yang dirancang "\n        "untuk mengevaluasi kinerja dan kepercayaan sistem Agentic AI di perusahaan modern. Seiring "\n        "dengan semakin bergantungnya organisasi di sektor jasa profesional pada agen AI otonom "\n        "untuk tugas-tugas kritikal, telah muncul kesenjangan kritis: para pengambil keputusan tidak "\n        "memiliki metrik terpadu yang andal untuk menilai keandalan dan produktivitas sistem ini. "\n        "Solusi yang diusulkan mengatasi tantangan ini dengan membangun pipeline arsitektur Medallion "\n        "dalam paradigma Data Lakehouse menggunakan Apache Spark. Empat sumber data heterogen "\n        "diintegrasikan: dataset operasional utama dalam format CSV berisi 5.500 catatan organisasi, "\n        "tolok ukur industri eksternal dalam JSON, log eksekusi sistem dalam CSV, dan data kutipan "\n        "akademik dari API OpenAlex. Setiap sumber mengalami pemetaan skema yang ketat, pemeriksaan "\n        "kualitas data, dan imputasi spesifik industri di lapisan pemrosesan Silver. Classifier "\n        "NLP berbasis regex mengontekstualisasikan kutipan makalah OpenAlex dengan memetakannya "\n        "langsung ke sektor bisnis yang relevan. Model pembelajaran mesin canggih diterapkan di "\n        "lapisan Gold, terdiri dari algoritma klasterisasi K-Means tanpa pengawasan yang divalidasi "\n        "dengan skor Silhouette 0,5276, dan classifier Regresi Logistik multikelas yang di-tune "\n        "dengan akurasi 56,01%. Data leakage dicegah dengan mengisolasi fitur klasterisasi dari "\n        "input klasifikasi. Model akhir yang dioptimalkan diserialisasi dan diekspor sebagai "\n        "artefak siap produksi. Pipeline otomatis ini memberikan profil kinerja yang bermakna "\n        "yang memungkinkan tim kepemimpinan mendasarkan keputusan strategis adopsi AI pada data "\n        "kuantitatif yang tervalidasi."',
    '"Proyek ini membangun pipeline data untuk mengukur seberapa baik kinerja sistem Agentic AI di perusahaan. "\n        "Saat ini, pengambil keputusan tidak punya angka pasti untuk mengevaluasi AI mereka dan hanya mengandalkan "\n        "tebakan dari log yang tersebar. Untuk mengatasi ini, kami menggunakan Apache Spark untuk membangun pipeline "\n        "berarsitektur Medallion (Bronze, Silver, Gold). Kami menggabungkan 4 jenis data: file CSV berisi 5.500 data "\n        "perusahaan, JSON tolok ukur industri, log sistem, dan kutipan OpenAlex. Pipeline ini membersihkan data, mengisi "\n        "nilai kosong berdasarkan rata-rata industri, dan mencocokkan jurnal akademik ke sektor bisnis menggunakan NLP. "\n        "Di layer Gold, kami memakai K-Means clustering (skor Silhouette 0,5276) untuk mengelompokkan perusahaan, dan "\n        "Regresi Logistik (akurasi 56,01%) untuk memprediksi produktivitas. Kami memastikan fitur clustering dipisah dari "\n        "model prediksi agar tidak ada kebocoran data (data leakage). Model akhir diekspor dan siap pakai, memberikan "\n        "angka nyata bagi pimpinan alih-alih sekadar asumsi."'
)

code = code.replace(
    '"Kemajuan pesat kecerdasan buatan selama satu dekade terakhir telah mengubah secara fundamental "\n        "cara bisnis beroperasi di hampir setiap sektor industri. Salah satu perkembangan paling "\n        "transformasional di bidang ini adalah munculnya Agentic AI\\u2014sistem perangkat lunak otonom "\n        "yang dapat secara mandiri merencanakan, mengeksekusi, dan beradaptasi sambil menjalankan "\n        "tugas kompleks multi-langkah di lingkungan dinamis. Tidak seperti otomatisasi berbasis aturan "\n        "tradisional yang mengikuti skrip yang telah ditentukan secara ketat, agen Agentic AI "\n        "memanfaatkan model bahasa besar dan pembelajaran penguatan untuk bernalar tentang tugas "\n        "mereka, berinteraksi dengan sistem eksternal dan API, serta menyesuaikan perilaku mereka "\n        "berdasarkan umpan balik real-time dan sinyal kontekstual. Sistem ini kini diterapkan di "\n        "lingkungan berisiko tinggi seperti manajemen layanan pelanggan, koordinasi rantai pasok, "\n        "audit keuangan, dan operasi TI perusahaan. Kemampuan mereka untuk beroperasi secara otonom "\n        "dan dalam skala besar menjadikannya aset yang sangat berharga bagi organisasi yang ingin "\n        "mengurangi biaya operasional, mempercepat pengambilan keputusan, dan mempertahankan "\n        "keunggulan kompetitif."',
    '"Agentic AI mulai mengubah cara perusahaan bekerja. Berbeda dengan bot biasa yang cuma mengikuti "\n        "skrip, sistem ini bisa merencanakan, menggunakan alat, dan beradaptasi sendiri. Perusahaan sekarang "\n        "memakai Agentic AI untuk layanan pelanggan, rantai pasok, dan operasi TI\\u2014terutama untuk "\n        "menekan biaya dan mempercepat keputusan."'
)

code = code.replace(
    '"Namun, adopsi Agentic AI juga menghadirkan tantangan tata kelola dan pengukuran yang "\n        "signifikan. Pemimpin bisnis dan manajer teknis membutuhkan bukti kuantitatif yang andal "\n        "untuk mengevaluasi apakah agen otonom ini berkinerja sesuai harapan, beroperasi dalam "\n        "parameter keamanan, dan memberikan peningkatan produktivitas yang terukur. Sayangnya, "\n        "telemetri operasional yang dihasilkan oleh agen-agen ini biasanya terfragmentasi di "\n        "berbagai sistem yang heterogen. Metrik kinerja ada dalam log aplikasi terisolasi yang "\n        "disimpan sebagai file teks tidak terstruktur, metadata organisasi disimpan dalam ekspor "\n        "CSV terstruktur dari portal perusahaan, dan data kontekstual tambahan\\u2014seperti tolok ukur "\n        "industri dan penelitian akademis\\u2014berada di database eksternal dan API publik. Tanpa "\n        "pipeline rekayasa data terpusat yang dapat mengumpulkan, membersihkan, mengintegrasikan, "\n        "dan menganalisis sumber-sumber yang berbeda ini, organisasi terpaksa mengevaluasi sistem "\n        "AI berdasarkan informasi yang tidak lengkap, terisolasi, dan seringkali tidak konsisten. "\n        "Hal ini membatasi kemampuan pengambil keputusan untuk membandingkan hasil, mendeteksi "\n        "anomali, dan memahami gambaran lengkap kinerja AI di seluruh organisasi mereka."',
    '"Tapi masalahnya: sangat sulit membuktikan bahwa agen AI ini benar-benar efektif. Manajer butuh "\n        "angka pasti, tapi datanya sering berserakan. Log sistem tersimpan di file teks, metrik perusahaan "\n        "di CSV, dan standar industri ada di API. Tanpa satu pipeline terpusat untuk membersihkan dan "\n        "menggabungkan data ini, perusahaan pada akhirnya hanya menebak apakah AI mereka benar-benar bekerja."'
)

code = code.replace(
    '"Proyek ini secara langsung mengatasi kesenjangan pengukuran yang dijelaskan di atas. "\n        "Kontribusi utama adalah desain dan implementasi pipeline data otomatis ujung-ke-ujung "\n        "yang mengubah data telemetri mentah dan terfragmentasi menjadi profil kinerja terstruktur "\n        "dan dapat dianalisis untuk kepemimpinan Agentic AI. Dibangun di atas Apache Spark dan "\n        "mengikuti pola arsitektur data Medallion, pipeline ini memproses empat sumber data yang "\n        "berbeda melalui alur kerja transformasi tiga lapis. Lapisan Bronze mengumpulkan file "\n        "mentah dalam format aslinya sambil mempertahankan metadata audit. Lapisan Silver "\n        "melakukan operasi pembersihan\\u2014termasuk deduplikasi, konversi tipe, imputasi null spesifik "\n        "industri, derivasi metrik efisiensi, dan pemetaan kontekstual kutipan ilmiah berbasis "\n        "NLP\\u2014untuk menghasilkan dataset yang bersih dan terpadu. Lapisan Gold menerapkan algoritma "\n        "pembelajaran mesin canggih untuk menghasilkan wawasan prediktif dan klasifikasi kinerja. "\n        "Hasil akhir dirancang untuk memberikan para pemimpin bisnis profil yang andal dan "\n        "berbasis data yang mendukung keputusan strategis mengenai adopsi dan investasi AI."',
    '"Proyek ini menyelesaikan masalah pengukuran tersebut. Kami membangun pipeline Medallion "\n        "berbasis Spark untuk mengubah log mentah menjadi profil kinerja yang jelas. Lapisan Bronze "\n        "menyimpan data mentah. Lapisan Silver membersihkannya, mengisi nilai kosong, dan "\n        "menggunakan NLP untuk memetakan kutipan akademik ke sektor bisnis. Terakhir, lapisan "\n        "Gold menerapkan machine learning untuk memprediksi kinerja. Hasil akhirnya adalah dataset "\n        "andal yang membantu pimpinan membuat keputusan berbasis data tentang sistem AI mereka."'
)

code = code.replace(
    '"Pipeline data adalah arsitektur dasar yang mengotomatiskan proses ujung-ke-ujung dari "\n        "ekstraksi data dari sistem sumber, transformasi melalui operasi pembersihan dan "\n        "pengayaan, dan pemuatan ke repositori penyimpanan target untuk analisis. Di lingkungan "\n        "perusahaan, pipeline data sangat penting untuk menangani keragaman, volume, dan kecepatan "\n        "data operasional yang dihasilkan oleh aplikasi modern. Secara historis, organisasi "\n        "mengandalkan Gudang Data relasional, yang menawarkan jaminan transaksional yang kuat "\n        "dan kinerja kueri tetapi mahal untuk diskalakan dan kurang cocok untuk data "\n        "semi-terstruktur atau tidak terstruktur. Di sisi lain, Danau Data menyediakan "\n        "penyimpanan hemat biaya untuk data mentah dalam format aslinya tetapi tidak memiliki "\n        "dukungan transaksi ACID dan mengalami penurunan kinerja saat di-kueri secara langsung. "\n        "Arsitektur Data Lakehouse muncul sebagai respons terhadap keterbatasan ini, menggabungkan "\n        "penegakan skema dan manajemen transaksi gudang data dengan model penyimpanan fleksibel "\n        "danau data. Implementasi Lakehouse biasanya menggunakan format kolom terbuka seperti "\n        "Apache Parquet untuk menyimpan data di penyimpanan objek cloud, sambil memanfaatkan "\n        "mesin kueri seperti Apache Spark untuk menyediakan operasi transaksional, evolusi skema, "\n        "dan kemampuan pembelajaran mesin langsung pada data yang disimpan [1]."',
    '"Pipeline data yang solid sangat penting untuk menangani volume data perusahaan yang besar. "\n        "Data Warehouse tradisional terlalu kaku untuk log semi-terstruktur, sementara Data Lake kurang "\n        "aman untuk transaksi. Arsitektur Data Lakehouse mengatasi masalah ini dengan menggabungkan "\n        "fleksibilitas lake dan keandalan warehouse. Ia menggunakan format kolom seperti Parquet dan mesin "\n        "komputasi seperti Apache Spark untuk memproses data dan menjalankan machine learning secara langsung (Armbrust et al., 2021)."'
)

code = code.replace(
    '"Tiga penelitian sebelumnya memberikan landasan teoretis dan panduan metodologis untuk "\n        "proyek ini. Pertama, karya seminal oleh Armbrust et al. (2021) memperkenalkan konsep "\n        "Lakehouse dan menunjukkan melalui analisis empiris bahwa organisasi yang mengadopsi "\n        "arsitektur ini dapat secara signifikan mengurangi duplikasi data dan kompleksitas "\n        "pipeline sambil mempertahankan satu sumber kebenaran untuk dasbor intelijen bisnis "\n        "dan beban kerja pembelajaran mesin canggih [1]. Kedua, Zaharia et al. (2016) menetapkan "\n        "Apache Spark sebagai mesin analitik terpadu untuk pemrosesan data skala besar, "\n        "menunjukkan bahwa model komputasi memori terdistribusinya mencapai throughput tinggi "\n        "dan latensi rendah untuk operasi join kompleks pada dataset besar\\u2014persis seperti yang "\n        "dibutuhkan untuk mengintegrasikan log telemetri heterogen dari beberapa sumber Agentic "\n        "AI [2]. Ketiga, penelitian terbaru dalam tata kelola AI dan kepercayaan telah menyoroti "\n        "kebutuhan akan kerangka empiris yang menggabungkan telemetri eksekusi operasional dengan "\n        "tolok ukur validasi eksternal, termasuk metrik kutipan ilmiah dari database seperti "\n        "OpenAlex, untuk membangun keyakinan dalam proses pengambilan keputusan agen otonom [3]. "\n        "Studi-studi ini secara kolektif membenarkan pilihan arsitektural dan pendekatan "\n        "metodologis yang diadopsi dalam proyek ini."',
    '"Proyek ini dibangun berdasarkan tiga temuan utama. Pertama, model Lakehouse mengurangi duplikasi data "\n        "dan menyederhanakan pipeline (Armbrust et al., 2021). Kedua, pemrosesan in-memory Apache Spark sangat "\n        "ideal untuk menggabungkan dataset besar yang kompleks (Zaharia et al., 2016)\\u2014tepat seperti yang kami "\n        "butuhkan untuk log Agentic AI. Terakhir, riset terbaru menyoroti bahwa menggabungkan log sistem dengan "\n        "data eksternal\\u2014seperti kutipan OpenAlex\\u2014sangat penting untuk mengevaluasi keandalan agen AI di "\n        "dunia nyata (Priem et al., 2022). Tiga paper ini yang mendasari pilihan arsitektur kami."'
)

code = code.replace(
    '"Bagian metodologi menjelaskan pendekatan sistematis yang digunakan untuk merancang, "\n        "mengembangkan, dan memvalidasi pipeline rekayasa data yang diusulkan. Metodologi yang "\n        "terdefinisi dengan baik sangat penting untuk memastikan bahwa hasil proyek selaras "\n        "dengan tujuan yang dinyatakan, memenuhi standar akademik dan profesional, serta dapat "\n        "direproduksi dalam konteks organisasi lain. Bab ini mencakup pemilihan dan justifikasi "\n        "kerangka kerja proyek secara keseluruhan, identifikasi dan deskripsi empat sumber data "\n        "yang digunakan sebagai input, prosedur untuk ingesti dan pembersihan data, arsitektur "\n        "penyimpanan dan alasannya, serta integrasi algoritma kecerdasan buatan dalam alur kerja "\n        "pemrosesan. Setiap komponen dijelaskan dengan kedalaman teknis yang cukup untuk "\n        "memungkinkan pembaca memahami baik keputusan desain tingkat tinggi maupun detail "\n        "implementasi spesifik yang membuat pipeline ini tangguh, terukur, dan siap produksi."',
    '"Bagian ini menguraikan cara kami merancang, membangun, dan menguji pipeline data. "\n        "Metodologi yang jelas memastikan proyek mencapai tujuannya dan mudah direproduksi nanti. "\n        "Kami membahas pilihan framework, empat sumber data yang dipakai, proses ETL, keputusan "\n        "penyimpanan, dan implementasi machine learning di layer Gold."'
)

code = code.replace(
    '"Pendekatan rekayasa mengikuti pola Arsitektur Medallion, yang mengatur pemrosesan "\n        "data ke dalam tiga lapisan yang disempurnakan secara progresif. Lapisan Bronze berfungsi "\n        "sebagai zona pendaratan di mana data mentah diingesti dengan fidelitas penuh dan "\n        "transformasi minimal. Lapisan Silver melakukan pembersihan, jaminan kualitas, dan "\n        "operasi integrasi untuk menghasilkan dataset yang konsisten dan andal. Lapisan Gold "\n        "mengagregasi data yang telah dibersihkan dan menerapkan model analitis dan pembelajaran "\n        "mesin untuk menghasilkan wawasan dan prediksi tingkat bisnis. Pola arsitektural ini "\n        "diadopsi secara luas di industri karena menyediakan pemisahan kepentingan yang jelas, "\n        "memungkinkan peningkatan kualitas data secara bertahap, dan mendukung pola ingesti "\n        "batch dan streaming dalam satu kerangka kerja. Sub-bagian berikut merinci setiap "\n        "aspek metodologi, dimulai dengan pemilihan CRISP-DM sebagai kerangka manajemen proyek "\n        "secara keseluruhan."',
    '"Kami menggunakan pola Arsitektur Medallion. Lapisan Bronze menyimpan data mentah apa adanya. "\n        "Lapisan Silver membersihkan dan mengintegrasikan data tersebut. Lapisan Gold menerapkan "\n        "analitik dan machine learning. Pengaturan ini menjaga kode tetap rapi, menangani data "\n        "buruk secara bertahap, dan sudah jadi standar industri. Keseluruhan proyek ini kami "\n        "kelola menggunakan kerangka kerja CRISP-DM."'
)

code = code.replace(
    '("19 Juni 2026", "Code Refactoring",\n         "Mengoptimalkan strategi join PySpark dan implementasi CrossValidator untuk model pembelajaran mesin lapisan Gold."),',
    '("19 Juni 2026", "Code Refactoring",\n         "Pakai Claude untuk optimasi strategi join PySpark. Prompt: \'Saya ada bottleneck memori di proses join Silver layer. Gimana cara optimasinya di PySpark tanpa pakai Pandas?\'"),'
)

code = code.replace(
    '("20 Juni 2026", "Draf Proposal",\n         "Meninjau celah dokumentasi teknis, menyusun bagian metodologi, dan menyelaraskan konten dengan persyaratan rubrik."),',
    '("20 Juni 2026", "Draf Proposal",\n         "Pakai ChatGPT untuk menstrukturisasi bagian metodologi. Prompt: \'Tolong buatkan outline bagian metodologi untuk proyek data engineering CRISP-DM berdasarkan rubrik ini.\'"),'
)

code = code.replace(
    '("20 Juni 2026", "Desain Sistem",\n         "Menyempurnakan definisi Star Schema, deskripsi use case, dan dokumentasi strategi pengujian.")',
    '("20 Juni 2026", "Desain Sistem",\n         "Pakai Claude untuk brainstorming struktur Star Schema. Prompt: \'Beri saran desain Star Schema di mana tabel fakta melacak eksekusi agen AI dan dimensinya mencakup organisasi, config agen, dan konteks riset.\'")'
)

# SAVE
with open(SCRIPT, 'w', encoding='utf-8') as f:
    f.write(code)

print("Rewrite Complete. Starting generator...")
